name: CI/CD API
on: push
jobs:
  test:
    name: Test API
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Run Unit tests
        run: npm run test
      - name: Run e2e tests
        run: npm run test:e2e
