name: CI/CD API
on: push
jobs:
  test:
    name: Test API
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn ci
      - name: Run Lint
        run: yarn lint
      - name: Run Unit tests
        run: yarn test
      - name: Run e2e tests
        run: yarn test:e2e
